import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.containercategory}>
      <Head>
        <title>Fede Giobergia | Product & UI/UX Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         
HOLIS FUNCIONO

    </div>
  )
}
