import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Flex, Spacer, Grid, GridItem } from "@chakra-ui/react"
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()

  return (

    <> 
      <Head>
        <title>Fede Giobergia | Product & UI/UX Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex justify="space-evenly" align="center" direction="row" style={{height: '100%'}}>

        <Flex align="center"  justify="center" className={styles.category} onClick={() => router.push('/about-me')}>

          <div style={{fontSize: '32px', fontWeight: 'bold'}}>
            UX
          </div>

        </Flex>

        <Flex align="center" justify="center" className={styles.category}>
        
          <div style={{fontSize: '32px', fontWeight: 'bold'}}>
              UI
          </div>

        </Flex>
        
        <Flex align="center"  justify="center" className={styles.category}>
          
          <div style={{fontSize: '32px', fontWeight: 'bold'}}>
            About me
          </div>


        </Flex>

      </Flex>

          {/* <a href="https://nextjs.org/docs" className={styles.category}>
            <h2>Documentation &rarr;</h2>
          </a>

          <a href="https://nextjs.org/docs" className={styles.category}>
            <h2>Documentation &rarr;</h2>
          </a>

          <a href="https://nextjs.org/docs" className={styles.category}>
            <h2>Documentation &rarr;</h2>
          </a> */}

    </>
  )
}
