import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Flex, Spacer, Grid, GridItem, Box } from "@chakra-ui/react";
import { useRouter } from "next/router";
import { motion } from "framer-motion";
import { Swiper, SwiperSlide } from "swiper/react";
import { useSmallScreenDetector } from "./hooks";
import DrawerMenu from "./components/drawer";
import NavBar from "./components/navBar";
import avatar from "../public/fechesinfondo.png";
import LocationOnOutlinedIcon from "@material-ui/icons/LocationOnOutlined";
import WorkOutlineIcon from "@material-ui/icons/WorkOutline";
import Works from "./components/works";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Fede Giobergia | Product & UI/UX Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>

      <Flex direction="column" marginRight={"15%"} marginLeft={"15%"}>
        <Box boxSize="178px" marginBottom={40}>
          <Image
            objectFit="cover"
            src={avatar}
            alt="Ilustración de Fede Giobergia hecha por Leandro Amarillo"
          />
        </Box>

        <h1 class="presentation">
          {" "}
          Hola, soy <a class="highlighted">Fede Giobergia</a>
        </h1>

        <Flex
          direction="row"
          justify="start"
          align="center"
          style={{ color: "#b0b0b0" }}
        >
          <LocationOnOutlinedIcon />
          <p style={{ marginLeft: "8px", marginRight: "32px" }}>
            {" "}
            Santa Fe, Argentina (all around the world)
          </p>

          <WorkOutlineIcon />
          <p style={{ marginLeft: "8px", marginRight: "32px" }}>
            Product & UX/UI Designer
          </p>
        </Flex>

        <p>
          Me apasiona la interacción humana con el entorno digital. Durante toda
          mi carrera trabajé como desarrollador, redactor y community manager,
          lo que hoy en día me permite ser parte de todo el proceso de
          investigación, diseño e iteración de productos digitales.{" "}
        </p>

        <Flex justify="center" direction="row">
          <Works></Works>
        </Flex>
      </Flex>
    </>
  );
}
